CLASS zbp_c_mcp_prog_validate DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.

CLASS zbp_c_mcp_prog_validate IMPLEMENTATION.
ENDCLASS.
